### ISSUE TITLE
About weights4mcl.list

### ISSUE THREAD

**Issue by icruz1989** [ohdongha/CL_finder#1]
Dear author

Could you give me an example of the weight matrix? I ran the command with "-h" to see how to create the matrix but I did not find the answer.

Thank you

Ivan

**Comment by ohdongha** [comment]
Dear Ivan, 
I have uploaded the default weight matrix file to the "scripts" folder.  Could you check whether it's working or not?  

Since the last year I have made quite some improvement on the OrthNet pipeline.  I plan to upload the new version within this month, so please stay tuned. 

Thanks and cheers,
Dong-Ha
